/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.lcs.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.osb.lcs.model.LCSClusterNodeUptime;
import com.liferay.osb.lcs.service.LCSClusterNodeUptimeLocalServiceUtil;

/**
 * The extended model base implementation for the LCSClusterNodeUptime service. Represents a row in the &quot;OSBLCS_LCSClusterNodeUptime&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LCSClusterNodeUptimeImpl}.
 * </p>
 *
 * @author Igor Beslic
 * @see LCSClusterNodeUptimeImpl
 * @see LCSClusterNodeUptime
 * @generated
 */
@ProviderType
public abstract class LCSClusterNodeUptimeBaseImpl
	extends LCSClusterNodeUptimeModelImpl implements LCSClusterNodeUptime {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a l c s cluster node uptime model instance should use the {@link LCSClusterNodeUptime} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LCSClusterNodeUptimeLocalServiceUtil.addLCSClusterNodeUptime(this);
		}
		else {
			LCSClusterNodeUptimeLocalServiceUtil.updateLCSClusterNodeUptime(this);
		}
	}
}