/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.lcs.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.osb.lcs.model.LCSMetadata;
import com.liferay.osb.lcs.service.LCSMetadataLocalServiceUtil;

/**
 * The extended model base implementation for the LCSMetadata service. Represents a row in the &quot;OSBLCS_LCSMetadata&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LCSMetadataImpl}.
 * </p>
 *
 * @author Igor Beslic
 * @see LCSMetadataImpl
 * @see LCSMetadata
 * @generated
 */
@ProviderType
public abstract class LCSMetadataBaseImpl extends LCSMetadataModelImpl
	implements LCSMetadata {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a l c s metadata model instance should use the {@link LCSMetadata} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LCSMetadataLocalServiceUtil.addLCSMetadata(this);
		}
		else {
			LCSMetadataLocalServiceUtil.updateLCSMetadata(this);
		}
	}
}