/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.lcs.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the LCSClusterEntry service. Represents a row in the &quot;OSBLCS_LCSClusterEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.lcs.model.impl.LCSClusterEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.lcs.model.impl.LCSClusterEntryImpl}.
 * </p>
 *
 * @author Igor Beslic
 * @see LCSClusterEntry
 * @see com.liferay.osb.lcs.model.impl.LCSClusterEntryImpl
 * @see com.liferay.osb.lcs.model.impl.LCSClusterEntryModelImpl
 * @generated
 */
@ProviderType
public interface LCSClusterEntryModel extends BaseModel<LCSClusterEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a l c s cluster entry model instance should use the {@link LCSClusterEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this l c s cluster entry.
	 *
	 * @return the primary key of this l c s cluster entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this l c s cluster entry.
	 *
	 * @param primaryKey the primary key of this l c s cluster entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lcs cluster entry ID of this l c s cluster entry.
	 *
	 * @return the lcs cluster entry ID of this l c s cluster entry
	 */
	public long getLcsClusterEntryId();

	/**
	 * Sets the lcs cluster entry ID of this l c s cluster entry.
	 *
	 * @param lcsClusterEntryId the lcs cluster entry ID of this l c s cluster entry
	 */
	public void setLcsClusterEntryId(long lcsClusterEntryId);

	/**
	 * Returns the lcs project ID of this l c s cluster entry.
	 *
	 * @return the lcs project ID of this l c s cluster entry
	 */
	public long getLcsProjectId();

	/**
	 * Sets the lcs project ID of this l c s cluster entry.
	 *
	 * @param lcsProjectId the lcs project ID of this l c s cluster entry
	 */
	public void setLcsProjectId(long lcsProjectId);

	/**
	 * Returns the name of this l c s cluster entry.
	 *
	 * @return the name of this l c s cluster entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this l c s cluster entry.
	 *
	 * @param name the name of this l c s cluster entry
	 */
	public void setName(String name);

	/**
	 * Returns the description of this l c s cluster entry.
	 *
	 * @return the description of this l c s cluster entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this l c s cluster entry.
	 *
	 * @param description the description of this l c s cluster entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the elastic of this l c s cluster entry.
	 *
	 * @return the elastic of this l c s cluster entry
	 */
	public boolean getElastic();

	/**
	 * Returns <code>true</code> if this l c s cluster entry is elastic.
	 *
	 * @return <code>true</code> if this l c s cluster entry is elastic; <code>false</code> otherwise
	 */
	public boolean isElastic();

	/**
	 * Sets whether this l c s cluster entry is elastic.
	 *
	 * @param elastic the elastic of this l c s cluster entry
	 */
	public void setElastic(boolean elastic);

	/**
	 * Returns the high page load time of this l c s cluster entry.
	 *
	 * @return the high page load time of this l c s cluster entry
	 */
	public int getHighPageLoadTime();

	/**
	 * Sets the high page load time of this l c s cluster entry.
	 *
	 * @param highPageLoadTime the high page load time of this l c s cluster entry
	 */
	public void setHighPageLoadTime(int highPageLoadTime);

	/**
	 * Returns the location of this l c s cluster entry.
	 *
	 * @return the location of this l c s cluster entry
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this l c s cluster entry.
	 *
	 * @param location the location of this l c s cluster entry
	 */
	public void setLocation(String location);

	/**
	 * Returns the medium page load time of this l c s cluster entry.
	 *
	 * @return the medium page load time of this l c s cluster entry
	 */
	public int getMediumPageLoadTime();

	/**
	 * Sets the medium page load time of this l c s cluster entry.
	 *
	 * @param mediumPageLoadTime the medium page load time of this l c s cluster entry
	 */
	public void setMediumPageLoadTime(int mediumPageLoadTime);

	/**
	 * Returns the subscription type of this l c s cluster entry.
	 *
	 * @return the subscription type of this l c s cluster entry
	 */
	@AutoEscape
	public String getSubscriptionType();

	/**
	 * Sets the subscription type of this l c s cluster entry.
	 *
	 * @param subscriptionType the subscription type of this l c s cluster entry
	 */
	public void setSubscriptionType(String subscriptionType);

	/**
	 * Returns the type of this l c s cluster entry.
	 *
	 * @return the type of this l c s cluster entry
	 */
	public int getType();

	/**
	 * Sets the type of this l c s cluster entry.
	 *
	 * @param type the type of this l c s cluster entry
	 */
	public void setType(int type);

	/**
	 * Returns the archived of this l c s cluster entry.
	 *
	 * @return the archived of this l c s cluster entry
	 */
	public boolean getArchived();

	/**
	 * Returns <code>true</code> if this l c s cluster entry is archived.
	 *
	 * @return <code>true</code> if this l c s cluster entry is archived; <code>false</code> otherwise
	 */
	public boolean isArchived();

	/**
	 * Sets whether this l c s cluster entry is archived.
	 *
	 * @param archived the archived of this l c s cluster entry
	 */
	public void setArchived(boolean archived);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LCSClusterEntry lcsClusterEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LCSClusterEntry> toCacheModel();

	@Override
	public LCSClusterEntry toEscapedModel();

	@Override
	public LCSClusterEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}