/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.lcs.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LCSClusterEntryToken service. Represents a row in the &quot;OSBLCS_LCSClusterEntryToken&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.lcs.model.impl.LCSClusterEntryTokenModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.lcs.model.impl.LCSClusterEntryTokenImpl}.
 * </p>
 *
 * @author Igor Beslic
 * @see LCSClusterEntryToken
 * @see com.liferay.osb.lcs.model.impl.LCSClusterEntryTokenImpl
 * @see com.liferay.osb.lcs.model.impl.LCSClusterEntryTokenModelImpl
 * @generated
 */
@ProviderType
public interface LCSClusterEntryTokenModel extends BaseModel<LCSClusterEntryToken> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a l c s cluster entry token model instance should use the {@link LCSClusterEntryToken} interface instead.
	 */

	/**
	 * Returns the primary key of this l c s cluster entry token.
	 *
	 * @return the primary key of this l c s cluster entry token
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this l c s cluster entry token.
	 *
	 * @param primaryKey the primary key of this l c s cluster entry token
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lcs cluster entry token ID of this l c s cluster entry token.
	 *
	 * @return the lcs cluster entry token ID of this l c s cluster entry token
	 */
	public long getLcsClusterEntryTokenId();

	/**
	 * Sets the lcs cluster entry token ID of this l c s cluster entry token.
	 *
	 * @param lcsClusterEntryTokenId the lcs cluster entry token ID of this l c s cluster entry token
	 */
	public void setLcsClusterEntryTokenId(long lcsClusterEntryTokenId);

	/**
	 * Returns the user ID of this l c s cluster entry token.
	 *
	 * @return the user ID of this l c s cluster entry token
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this l c s cluster entry token.
	 *
	 * @param userId the user ID of this l c s cluster entry token
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this l c s cluster entry token.
	 *
	 * @return the user uuid of this l c s cluster entry token
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this l c s cluster entry token.
	 *
	 * @param userUuid the user uuid of this l c s cluster entry token
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this l c s cluster entry token.
	 *
	 * @return the create date of this l c s cluster entry token
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this l c s cluster entry token.
	 *
	 * @param createDate the create date of this l c s cluster entry token
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the lcs cluster entry ID of this l c s cluster entry token.
	 *
	 * @return the lcs cluster entry ID of this l c s cluster entry token
	 */
	public long getLcsClusterEntryId();

	/**
	 * Sets the lcs cluster entry ID of this l c s cluster entry token.
	 *
	 * @param lcsClusterEntryId the lcs cluster entry ID of this l c s cluster entry token
	 */
	public void setLcsClusterEntryId(long lcsClusterEntryId);

	/**
	 * Returns the content of this l c s cluster entry token.
	 *
	 * @return the content of this l c s cluster entry token
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this l c s cluster entry token.
	 *
	 * @param content the content of this l c s cluster entry token
	 */
	public void setContent(String content);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LCSClusterEntryToken lcsClusterEntryToken);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LCSClusterEntryToken> toCacheModel();

	@Override
	public LCSClusterEntryToken toEscapedModel();

	@Override
	public LCSClusterEntryToken toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}