/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.lcs.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LCSInvitation service. Represents a row in the &quot;OSBLCS_LCSInvitation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.lcs.model.impl.LCSInvitationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.lcs.model.impl.LCSInvitationImpl}.
 * </p>
 *
 * @author Igor Beslic
 * @see LCSInvitation
 * @see com.liferay.osb.lcs.model.impl.LCSInvitationImpl
 * @see com.liferay.osb.lcs.model.impl.LCSInvitationModelImpl
 * @generated
 */
@ProviderType
public interface LCSInvitationModel extends BaseModel<LCSInvitation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a l c s invitation model instance should use the {@link LCSInvitation} interface instead.
	 */

	/**
	 * Returns the primary key of this l c s invitation.
	 *
	 * @return the primary key of this l c s invitation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this l c s invitation.
	 *
	 * @param primaryKey the primary key of this l c s invitation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lcs invitation ID of this l c s invitation.
	 *
	 * @return the lcs invitation ID of this l c s invitation
	 */
	public long getLcsInvitationId();

	/**
	 * Sets the lcs invitation ID of this l c s invitation.
	 *
	 * @param lcsInvitationId the lcs invitation ID of this l c s invitation
	 */
	public void setLcsInvitationId(long lcsInvitationId);

	/**
	 * Returns the user ID of this l c s invitation.
	 *
	 * @return the user ID of this l c s invitation
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this l c s invitation.
	 *
	 * @param userId the user ID of this l c s invitation
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this l c s invitation.
	 *
	 * @return the user uuid of this l c s invitation
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this l c s invitation.
	 *
	 * @param userUuid the user uuid of this l c s invitation
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this l c s invitation.
	 *
	 * @return the create date of this l c s invitation
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this l c s invitation.
	 *
	 * @param createDate the create date of this l c s invitation
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the lcs project ID of this l c s invitation.
	 *
	 * @return the lcs project ID of this l c s invitation
	 */
	public long getLcsProjectId();

	/**
	 * Sets the lcs project ID of this l c s invitation.
	 *
	 * @param lcsProjectId the lcs project ID of this l c s invitation
	 */
	public void setLcsProjectId(long lcsProjectId);

	/**
	 * Returns the email address of this l c s invitation.
	 *
	 * @return the email address of this l c s invitation
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this l c s invitation.
	 *
	 * @param emailAddress the email address of this l c s invitation
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the lcs cluster entry ID of this l c s invitation.
	 *
	 * @return the lcs cluster entry ID of this l c s invitation
	 */
	public long getLcsClusterEntryId();

	/**
	 * Sets the lcs cluster entry ID of this l c s invitation.
	 *
	 * @param lcsClusterEntryId the lcs cluster entry ID of this l c s invitation
	 */
	public void setLcsClusterEntryId(long lcsClusterEntryId);

	/**
	 * Returns the role of this l c s invitation.
	 *
	 * @return the role of this l c s invitation
	 */
	public int getRole();

	/**
	 * Sets the role of this l c s invitation.
	 *
	 * @param role the role of this l c s invitation
	 */
	public void setRole(int role);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LCSInvitation lcsInvitation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LCSInvitation> toCacheModel();

	@Override
	public LCSInvitation toEscapedModel();

	@Override
	public LCSInvitation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}