/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.lcs.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LCSMessage service. Represents a row in the &quot;OSBLCS_LCSMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.lcs.model.impl.LCSMessageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.lcs.model.impl.LCSMessageImpl}.
 * </p>
 *
 * @author Igor Beslic
 * @see LCSMessage
 * @see com.liferay.osb.lcs.model.impl.LCSMessageImpl
 * @see com.liferay.osb.lcs.model.impl.LCSMessageModelImpl
 * @generated
 */
@ProviderType
public interface LCSMessageModel extends AttachedModel, BaseModel<LCSMessage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a l c s message model instance should use the {@link LCSMessage} interface instead.
	 */

	/**
	 * Returns the primary key of this l c s message.
	 *
	 * @return the primary key of this l c s message
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this l c s message.
	 *
	 * @param primaryKey the primary key of this l c s message
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lcs message ID of this l c s message.
	 *
	 * @return the lcs message ID of this l c s message
	 */
	public long getLcsMessageId();

	/**
	 * Sets the lcs message ID of this l c s message.
	 *
	 * @param lcsMessageId the lcs message ID of this l c s message
	 */
	public void setLcsMessageId(long lcsMessageId);

	/**
	 * Returns the create date of this l c s message.
	 *
	 * @return the create date of this l c s message
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this l c s message.
	 *
	 * @param createDate the create date of this l c s message
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this l c s message.
	 *
	 * @return the modified date of this l c s message
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this l c s message.
	 *
	 * @param modifiedDate the modified date of this l c s message
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the source message ID of this l c s message.
	 *
	 * @return the source message ID of this l c s message
	 */
	public long getSourceMessageId();

	/**
	 * Sets the source message ID of this l c s message.
	 *
	 * @param sourceMessageId the source message ID of this l c s message
	 */
	public void setSourceMessageId(long sourceMessageId);

	/**
	 * Returns the source system name of this l c s message.
	 *
	 * @return the source system name of this l c s message
	 */
	@AutoEscape
	public String getSourceSystemName();

	/**
	 * Sets the source system name of this l c s message.
	 *
	 * @param sourceSystemName the source system name of this l c s message
	 */
	public void setSourceSystemName(String sourceSystemName);

	/**
	 * Returns the fully qualified class name of this l c s message.
	 *
	 * @return the fully qualified class name of this l c s message
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this l c s message.
	 *
	 * @return the class name ID of this l c s message
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this l c s message.
	 *
	 * @param classNameId the class name ID of this l c s message
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this l c s message.
	 *
	 * @return the class p k of this l c s message
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this l c s message.
	 *
	 * @param classPK the class p k of this l c s message
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the content of this l c s message.
	 *
	 * @return the content of this l c s message
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this l c s message.
	 *
	 * @param content the content of this l c s message
	 */
	public void setContent(String content);

	/**
	 * Returns the end date of this l c s message.
	 *
	 * @return the end date of this l c s message
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this l c s message.
	 *
	 * @param endDate the end date of this l c s message
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the global of this l c s message.
	 *
	 * @return the global of this l c s message
	 */
	public boolean getGlobal();

	/**
	 * Returns <code>true</code> if this l c s message is global.
	 *
	 * @return <code>true</code> if this l c s message is global; <code>false</code> otherwise
	 */
	public boolean isGlobal();

	/**
	 * Sets whether this l c s message is global.
	 *
	 * @param global the global of this l c s message
	 */
	public void setGlobal(boolean global);

	/**
	 * Returns the severity level of this l c s message.
	 *
	 * @return the severity level of this l c s message
	 */
	public int getSeverityLevel();

	/**
	 * Sets the severity level of this l c s message.
	 *
	 * @param severityLevel the severity level of this l c s message
	 */
	public void setSeverityLevel(int severityLevel);

	/**
	 * Returns the type of this l c s message.
	 *
	 * @return the type of this l c s message
	 */
	public int getType();

	/**
	 * Sets the type of this l c s message.
	 *
	 * @param type the type of this l c s message
	 */
	public void setType(int type);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LCSMessage lcsMessage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LCSMessage> toCacheModel();

	@Override
	public LCSMessage toEscapedModel();

	@Override
	public LCSMessage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}