/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.lcs.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the LCSClusterNodeUptime service. Represents a row in the &quot;OSBLCS_LCSClusterNodeUptime&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.lcs.model.impl.LCSClusterNodeUptimeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.lcs.model.impl.LCSClusterNodeUptimeImpl}.
 * </p>
 *
 * @author Igor Beslic
 * @see LCSClusterNodeUptime
 * @see com.liferay.osb.lcs.model.impl.LCSClusterNodeUptimeImpl
 * @see com.liferay.osb.lcs.model.impl.LCSClusterNodeUptimeModelImpl
 * @generated
 */
@ProviderType
public interface LCSClusterNodeUptimeModel extends BaseModel<LCSClusterNodeUptime> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a l c s cluster node uptime model instance should use the {@link LCSClusterNodeUptime} interface instead.
	 */

	/**
	 * Returns the primary key of this l c s cluster node uptime.
	 *
	 * @return the primary key of this l c s cluster node uptime
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this l c s cluster node uptime.
	 *
	 * @param primaryKey the primary key of this l c s cluster node uptime
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lcs cluster node uptime ID of this l c s cluster node uptime.
	 *
	 * @return the lcs cluster node uptime ID of this l c s cluster node uptime
	 */
	public long getLcsClusterNodeUptimeId();

	/**
	 * Sets the lcs cluster node uptime ID of this l c s cluster node uptime.
	 *
	 * @param lcsClusterNodeUptimeId the lcs cluster node uptime ID of this l c s cluster node uptime
	 */
	public void setLcsClusterNodeUptimeId(long lcsClusterNodeUptimeId);

	/**
	 * Returns the lcs cluster node ID of this l c s cluster node uptime.
	 *
	 * @return the lcs cluster node ID of this l c s cluster node uptime
	 */
	public long getLcsClusterNodeId();

	/**
	 * Sets the lcs cluster node ID of this l c s cluster node uptime.
	 *
	 * @param lcsClusterNodeId the lcs cluster node ID of this l c s cluster node uptime
	 */
	public void setLcsClusterNodeId(long lcsClusterNodeId);

	/**
	 * Returns the start time of this l c s cluster node uptime.
	 *
	 * @return the start time of this l c s cluster node uptime
	 */
	public long getStartTime();

	/**
	 * Sets the start time of this l c s cluster node uptime.
	 *
	 * @param startTime the start time of this l c s cluster node uptime
	 */
	public void setStartTime(long startTime);

	/**
	 * Returns the end time of this l c s cluster node uptime.
	 *
	 * @return the end time of this l c s cluster node uptime
	 */
	public long getEndTime();

	/**
	 * Sets the end time of this l c s cluster node uptime.
	 *
	 * @param endTime the end time of this l c s cluster node uptime
	 */
	public void setEndTime(long endTime);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LCSClusterNodeUptime lcsClusterNodeUptime);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LCSClusterNodeUptime> toCacheModel();

	@Override
	public LCSClusterNodeUptime toEscapedModel();

	@Override
	public LCSClusterNodeUptime toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}