/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.lcs.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LCSNotification service. Represents a row in the &quot;OSBLCS_LCSNotification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.lcs.model.impl.LCSNotificationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.lcs.model.impl.LCSNotificationImpl}.
 * </p>
 *
 * @author Igor Beslic
 * @see LCSNotification
 * @see com.liferay.osb.lcs.model.impl.LCSNotificationImpl
 * @see com.liferay.osb.lcs.model.impl.LCSNotificationModelImpl
 * @generated
 */
@ProviderType
public interface LCSNotificationModel extends AttachedModel,
	BaseModel<LCSNotification> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a l c s notification model instance should use the {@link LCSNotification} interface instead.
	 */

	/**
	 * Returns the primary key of this l c s notification.
	 *
	 * @return the primary key of this l c s notification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this l c s notification.
	 *
	 * @param primaryKey the primary key of this l c s notification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lcs notification ID of this l c s notification.
	 *
	 * @return the lcs notification ID of this l c s notification
	 */
	public long getLcsNotificationId();

	/**
	 * Sets the lcs notification ID of this l c s notification.
	 *
	 * @param lcsNotificationId the lcs notification ID of this l c s notification
	 */
	public void setLcsNotificationId(long lcsNotificationId);

	/**
	 * Returns the user ID of this l c s notification.
	 *
	 * @return the user ID of this l c s notification
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this l c s notification.
	 *
	 * @param userId the user ID of this l c s notification
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this l c s notification.
	 *
	 * @return the user uuid of this l c s notification
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this l c s notification.
	 *
	 * @param userUuid the user uuid of this l c s notification
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this l c s notification.
	 *
	 * @return the create date of this l c s notification
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this l c s notification.
	 *
	 * @param createDate the create date of this l c s notification
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this l c s notification.
	 *
	 * @return the modified date of this l c s notification
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this l c s notification.
	 *
	 * @param modifiedDate the modified date of this l c s notification
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this l c s notification.
	 *
	 * @return the fully qualified class name of this l c s notification
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this l c s notification.
	 *
	 * @return the class name ID of this l c s notification
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this l c s notification.
	 *
	 * @param classNameId the class name ID of this l c s notification
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this l c s notification.
	 *
	 * @return the class p k of this l c s notification
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this l c s notification.
	 *
	 * @param classPK the class p k of this l c s notification
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the enabled of this l c s notification.
	 *
	 * @return the enabled of this l c s notification
	 */
	public boolean getEnabled();

	/**
	 * Returns <code>true</code> if this l c s notification is enabled.
	 *
	 * @return <code>true</code> if this l c s notification is enabled; <code>false</code> otherwise
	 */
	public boolean isEnabled();

	/**
	 * Sets whether this l c s notification is enabled.
	 *
	 * @param enabled the enabled of this l c s notification
	 */
	public void setEnabled(boolean enabled);

	/**
	 * Returns the type of this l c s notification.
	 *
	 * @return the type of this l c s notification
	 */
	public int getType();

	/**
	 * Sets the type of this l c s notification.
	 *
	 * @param type the type of this l c s notification
	 */
	public void setType(int type);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LCSNotification lcsNotification);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LCSNotification> toCacheModel();

	@Override
	public LCSNotification toEscapedModel();

	@Override
	public LCSNotification toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}