/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.lcs.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LCSNotificationAuditEntry service. Represents a row in the &quot;OSBLCS_LCSNotificationAuditEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.lcs.model.impl.LCSNotificationAuditEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.lcs.model.impl.LCSNotificationAuditEntryImpl}.
 * </p>
 *
 * @author Igor Beslic
 * @see LCSNotificationAuditEntry
 * @see com.liferay.osb.lcs.model.impl.LCSNotificationAuditEntryImpl
 * @see com.liferay.osb.lcs.model.impl.LCSNotificationAuditEntryModelImpl
 * @generated
 */
@ProviderType
public interface LCSNotificationAuditEntryModel extends BaseModel<LCSNotificationAuditEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a l c s notification audit entry model instance should use the {@link LCSNotificationAuditEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this l c s notification audit entry.
	 *
	 * @return the primary key of this l c s notification audit entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this l c s notification audit entry.
	 *
	 * @param primaryKey the primary key of this l c s notification audit entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lcs notification audit entry ID of this l c s notification audit entry.
	 *
	 * @return the lcs notification audit entry ID of this l c s notification audit entry
	 */
	public long getLcsNotificationAuditEntryId();

	/**
	 * Sets the lcs notification audit entry ID of this l c s notification audit entry.
	 *
	 * @param lcsNotificationAuditEntryId the lcs notification audit entry ID of this l c s notification audit entry
	 */
	public void setLcsNotificationAuditEntryId(long lcsNotificationAuditEntryId);

	/**
	 * Returns the user ID of this l c s notification audit entry.
	 *
	 * @return the user ID of this l c s notification audit entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this l c s notification audit entry.
	 *
	 * @param userId the user ID of this l c s notification audit entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this l c s notification audit entry.
	 *
	 * @return the user uuid of this l c s notification audit entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this l c s notification audit entry.
	 *
	 * @param userUuid the user uuid of this l c s notification audit entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this l c s notification audit entry.
	 *
	 * @return the create date of this l c s notification audit entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this l c s notification audit entry.
	 *
	 * @param createDate the create date of this l c s notification audit entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the lcs cluster node ID of this l c s notification audit entry.
	 *
	 * @return the lcs cluster node ID of this l c s notification audit entry
	 */
	public long getLcsClusterNodeId();

	/**
	 * Sets the lcs cluster node ID of this l c s notification audit entry.
	 *
	 * @param lcsClusterNodeId the lcs cluster node ID of this l c s notification audit entry
	 */
	public void setLcsClusterNodeId(long lcsClusterNodeId);

	/**
	 * Returns the type of this l c s notification audit entry.
	 *
	 * @return the type of this l c s notification audit entry
	 */
	public int getType();

	/**
	 * Sets the type of this l c s notification audit entry.
	 *
	 * @param type the type of this l c s notification audit entry
	 */
	public void setType(int type);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LCSNotificationAuditEntry lcsNotificationAuditEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LCSNotificationAuditEntry> toCacheModel();

	@Override
	public LCSNotificationAuditEntry toEscapedModel();

	@Override
	public LCSNotificationAuditEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}