/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.lcs.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the LCSRole service. Represents a row in the &quot;OSBLCS_LCSRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.lcs.model.impl.LCSRoleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.lcs.model.impl.LCSRoleImpl}.
 * </p>
 *
 * @author Igor Beslic
 * @see LCSRole
 * @see com.liferay.osb.lcs.model.impl.LCSRoleImpl
 * @see com.liferay.osb.lcs.model.impl.LCSRoleModelImpl
 * @generated
 */
@ProviderType
public interface LCSRoleModel extends BaseModel<LCSRole> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a l c s role model instance should use the {@link LCSRole} interface instead.
	 */

	/**
	 * Returns the primary key of this l c s role.
	 *
	 * @return the primary key of this l c s role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this l c s role.
	 *
	 * @param primaryKey the primary key of this l c s role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lcs role ID of this l c s role.
	 *
	 * @return the lcs role ID of this l c s role
	 */
	public long getLcsRoleId();

	/**
	 * Sets the lcs role ID of this l c s role.
	 *
	 * @param lcsRoleId the lcs role ID of this l c s role
	 */
	public void setLcsRoleId(long lcsRoleId);

	/**
	 * Returns the user ID of this l c s role.
	 *
	 * @return the user ID of this l c s role
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this l c s role.
	 *
	 * @param userId the user ID of this l c s role
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this l c s role.
	 *
	 * @return the user uuid of this l c s role
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this l c s role.
	 *
	 * @param userUuid the user uuid of this l c s role
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the lcs project ID of this l c s role.
	 *
	 * @return the lcs project ID of this l c s role
	 */
	public long getLcsProjectId();

	/**
	 * Sets the lcs project ID of this l c s role.
	 *
	 * @param lcsProjectId the lcs project ID of this l c s role
	 */
	public void setLcsProjectId(long lcsProjectId);

	/**
	 * Returns the lcs cluster entry ID of this l c s role.
	 *
	 * @return the lcs cluster entry ID of this l c s role
	 */
	public long getLcsClusterEntryId();

	/**
	 * Sets the lcs cluster entry ID of this l c s role.
	 *
	 * @param lcsClusterEntryId the lcs cluster entry ID of this l c s role
	 */
	public void setLcsClusterEntryId(long lcsClusterEntryId);

	/**
	 * Returns the role of this l c s role.
	 *
	 * @return the role of this l c s role
	 */
	public int getRole();

	/**
	 * Sets the role of this l c s role.
	 *
	 * @param role the role of this l c s role
	 */
	public void setRole(int role);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LCSRole lcsRole);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LCSRole> toCacheModel();

	@Override
	public LCSRole toEscapedModel();

	@Override
	public LCSRole toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}