/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.lcs.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the UserLCSMessage service. Represents a row in the &quot;OSBLCS_UserLCSMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.lcs.model.impl.UserLCSMessageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.lcs.model.impl.UserLCSMessageImpl}.
 * </p>
 *
 * @author Igor Beslic
 * @see UserLCSMessage
 * @see com.liferay.osb.lcs.model.impl.UserLCSMessageImpl
 * @see com.liferay.osb.lcs.model.impl.UserLCSMessageModelImpl
 * @generated
 */
@ProviderType
public interface UserLCSMessageModel extends BaseModel<UserLCSMessage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user l c s message model instance should use the {@link UserLCSMessage} interface instead.
	 */

	/**
	 * Returns the primary key of this user l c s message.
	 *
	 * @return the primary key of this user l c s message
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user l c s message.
	 *
	 * @param primaryKey the primary key of this user l c s message
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user lcs message ID of this user l c s message.
	 *
	 * @return the user lcs message ID of this user l c s message
	 */
	public long getUserLcsMessageId();

	/**
	 * Sets the user lcs message ID of this user l c s message.
	 *
	 * @param userLcsMessageId the user lcs message ID of this user l c s message
	 */
	public void setUserLcsMessageId(long userLcsMessageId);

	/**
	 * Returns the user ID of this user l c s message.
	 *
	 * @return the user ID of this user l c s message
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user l c s message.
	 *
	 * @param userId the user ID of this user l c s message
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user l c s message.
	 *
	 * @return the user uuid of this user l c s message
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user l c s message.
	 *
	 * @param userUuid the user uuid of this user l c s message
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the lcs message ID of this user l c s message.
	 *
	 * @return the lcs message ID of this user l c s message
	 */
	public long getLcsMessageId();

	/**
	 * Sets the lcs message ID of this user l c s message.
	 *
	 * @param lcsMessageId the lcs message ID of this user l c s message
	 */
	public void setLcsMessageId(long lcsMessageId);

	/**
	 * Returns the hidden of this user l c s message.
	 *
	 * @return the hidden of this user l c s message
	 */
	public boolean getHidden();

	/**
	 * Returns <code>true</code> if this user l c s message is hidden.
	 *
	 * @return <code>true</code> if this user l c s message is hidden; <code>false</code> otherwise
	 */
	public boolean isHidden();

	/**
	 * Sets whether this user l c s message is hidden.
	 *
	 * @param hidden the hidden of this user l c s message
	 */
	public void setHidden(boolean hidden);

	/**
	 * Returns the read of this user l c s message.
	 *
	 * @return the read of this user l c s message
	 */
	public boolean getRead();

	/**
	 * Returns <code>true</code> if this user l c s message is read.
	 *
	 * @return <code>true</code> if this user l c s message is read; <code>false</code> otherwise
	 */
	public boolean isRead();

	/**
	 * Sets whether this user l c s message is read.
	 *
	 * @param read the read of this user l c s message
	 */
	public void setRead(boolean read);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UserLCSMessage userLCSMessage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UserLCSMessage> toCacheModel();

	@Override
	public UserLCSMessage toEscapedModel();

	@Override
	public UserLCSMessage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}