/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.ldn.documentation.project.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.osb.ldn.documentation.project.model.DocumentationProject;
import com.liferay.osb.ldn.documentation.project.model.DocumentationProjectModel;
import com.liferay.osb.ldn.documentation.project.model.DocumentationProjectSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DocumentationProject service. Represents a row in the &quot;OSB_LDN_DocumentationProject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link DocumentationProjectModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DocumentationProjectImpl}.
 * </p>
 *
 * @author Ryan Park
 * @see DocumentationProjectImpl
 * @see DocumentationProject
 * @see DocumentationProjectModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class DocumentationProjectModelImpl extends BaseModelImpl<DocumentationProject>
	implements DocumentationProjectModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a documentation project model instance should use the {@link DocumentationProject} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_LDN_DocumentationProject";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "documentationProjectId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "name", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "iconFileName", Types.VARCHAR },
			{ "status", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("documentationProjectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("iconFileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table OSB_LDN_DocumentationProject (uuid_ VARCHAR(75) null,documentationProjectId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,description STRING null,iconFileName VARCHAR(75) null,status INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table OSB_LDN_DocumentationProject";
	public static final String ORDER_BY_JPQL = " ORDER BY documentationProject.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_LDN_DocumentationProject.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.ldn.documentation.project.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.ldn.documentation.project.model.DocumentationProject"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.ldn.documentation.project.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.ldn.documentation.project.model.DocumentationProject"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.osb.ldn.documentation.project.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.ldn.documentation.project.model.DocumentationProject"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long NAME_COLUMN_BITMASK = 2L;
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DocumentationProject toModel(
		DocumentationProjectSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DocumentationProject model = new DocumentationProjectImpl();

		model.setUuid(soapModel.getUuid());
		model.setDocumentationProjectId(soapModel.getDocumentationProjectId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());
		model.setIconFileName(soapModel.getIconFileName());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DocumentationProject> toModels(
		DocumentationProjectSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DocumentationProject> models = new ArrayList<DocumentationProject>(soapModels.length);

		for (DocumentationProjectSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.osb.ldn.documentation.project.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.ldn.documentation.project.model.DocumentationProject"));

	public DocumentationProjectModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _documentationProjectId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDocumentationProjectId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _documentationProjectId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DocumentationProject.class;
	}

	@Override
	public String getModelClassName() {
		return DocumentationProject.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("documentationProjectId", getDocumentationProjectId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());
		attributes.put("description", getDescription());
		attributes.put("iconFileName", getIconFileName());
		attributes.put("status", getStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long documentationProjectId = (Long)attributes.get(
				"documentationProjectId");

		if (documentationProjectId != null) {
			setDocumentationProjectId(documentationProjectId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String iconFileName = (String)attributes.get("iconFileName");

		if (iconFileName != null) {
			setIconFileName(iconFileName);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getDocumentationProjectId() {
		return _documentationProjectId;
	}

	@Override
	public void setDocumentationProjectId(long documentationProjectId) {
		_documentationProjectId = documentationProjectId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public String getIconFileName() {
		if (_iconFileName == null) {
			return StringPool.BLANK;
		}
		else {
			return _iconFileName;
		}
	}

	@Override
	public void setIconFileName(String iconFileName) {
		_iconFileName = iconFileName;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				DocumentationProject.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			DocumentationProject.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DocumentationProject toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DocumentationProject)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DocumentationProjectImpl documentationProjectImpl = new DocumentationProjectImpl();

		documentationProjectImpl.setUuid(getUuid());
		documentationProjectImpl.setDocumentationProjectId(getDocumentationProjectId());
		documentationProjectImpl.setCompanyId(getCompanyId());
		documentationProjectImpl.setUserId(getUserId());
		documentationProjectImpl.setUserName(getUserName());
		documentationProjectImpl.setCreateDate(getCreateDate());
		documentationProjectImpl.setModifiedDate(getModifiedDate());
		documentationProjectImpl.setName(getName());
		documentationProjectImpl.setDescription(getDescription());
		documentationProjectImpl.setIconFileName(getIconFileName());
		documentationProjectImpl.setStatus(getStatus());

		documentationProjectImpl.resetOriginalValues();

		return documentationProjectImpl;
	}

	@Override
	public int compareTo(DocumentationProject documentationProject) {
		int value = 0;

		value = getName().compareToIgnoreCase(documentationProject.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DocumentationProject)) {
			return false;
		}

		DocumentationProject documentationProject = (DocumentationProject)obj;

		long primaryKey = documentationProject.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		DocumentationProjectModelImpl documentationProjectModelImpl = this;

		documentationProjectModelImpl._originalUuid = documentationProjectModelImpl._uuid;

		documentationProjectModelImpl._originalCompanyId = documentationProjectModelImpl._companyId;

		documentationProjectModelImpl._setOriginalCompanyId = false;

		documentationProjectModelImpl._setModifiedDate = false;

		documentationProjectModelImpl._originalName = documentationProjectModelImpl._name;

		documentationProjectModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DocumentationProject> toCacheModel() {
		DocumentationProjectCacheModel documentationProjectCacheModel = new DocumentationProjectCacheModel();

		documentationProjectCacheModel.uuid = getUuid();

		String uuid = documentationProjectCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			documentationProjectCacheModel.uuid = null;
		}

		documentationProjectCacheModel.documentationProjectId = getDocumentationProjectId();

		documentationProjectCacheModel.companyId = getCompanyId();

		documentationProjectCacheModel.userId = getUserId();

		documentationProjectCacheModel.userName = getUserName();

		String userName = documentationProjectCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			documentationProjectCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			documentationProjectCacheModel.createDate = createDate.getTime();
		}
		else {
			documentationProjectCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			documentationProjectCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			documentationProjectCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		documentationProjectCacheModel.name = getName();

		String name = documentationProjectCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			documentationProjectCacheModel.name = null;
		}

		documentationProjectCacheModel.description = getDescription();

		String description = documentationProjectCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			documentationProjectCacheModel.description = null;
		}

		documentationProjectCacheModel.iconFileName = getIconFileName();

		String iconFileName = documentationProjectCacheModel.iconFileName;

		if ((iconFileName != null) && (iconFileName.length() == 0)) {
			documentationProjectCacheModel.iconFileName = null;
		}

		documentationProjectCacheModel.status = getStatus();

		return documentationProjectCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", documentationProjectId=");
		sb.append(getDocumentationProjectId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", iconFileName=");
		sb.append(getIconFileName());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append(
			"com.liferay.osb.ldn.documentation.project.model.DocumentationProject");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentationProjectId</column-name><column-value><![CDATA[");
		sb.append(getDocumentationProjectId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>iconFileName</column-name><column-value><![CDATA[");
		sb.append(getIconFileName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = DocumentationProject.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			DocumentationProject.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _documentationProjectId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private String _description;
	private String _iconFileName;
	private int _status;
	private long _columnBitmask;
	private DocumentationProject _escapedModel;
}