/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.lcs.service.base;

import com.liferay.osb.lcs.model.LCSClusterNode;
import com.liferay.osb.lcs.service.LCSClusterNodeService;
import com.liferay.osb.lcs.service.persistence.LCSClusterEntryPersistence;
import com.liferay.osb.lcs.service.persistence.LCSClusterEntryTokenPersistence;
import com.liferay.osb.lcs.service.persistence.LCSClusterNodeFinder;
import com.liferay.osb.lcs.service.persistence.LCSClusterNodePersistence;
import com.liferay.osb.lcs.service.persistence.LCSClusterNodeUptimePersistence;
import com.liferay.osb.lcs.service.persistence.LCSInvitationPersistence;
import com.liferay.osb.lcs.service.persistence.LCSMessagePersistence;
import com.liferay.osb.lcs.service.persistence.LCSMetadataPersistence;
import com.liferay.osb.lcs.service.persistence.LCSNotificationAuditEntryPersistence;
import com.liferay.osb.lcs.service.persistence.LCSNotificationPersistence;
import com.liferay.osb.lcs.service.persistence.LCSPatchEntryPersistence;
import com.liferay.osb.lcs.service.persistence.LCSProjectPersistence;
import com.liferay.osb.lcs.service.persistence.LCSRolePersistence;
import com.liferay.osb.lcs.service.persistence.LCSSubscriptionEntryPersistence;
import com.liferay.osb.lcs.service.persistence.UserLCSMessagePersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the l c s cluster node remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.osb.lcs.service.impl.LCSClusterNodeServiceImpl}.
 * </p>
 *
 * @author Igor Beslic
 * @see com.liferay.osb.lcs.service.impl.LCSClusterNodeServiceImpl
 * @see com.liferay.osb.lcs.service.LCSClusterNodeServiceUtil
 * @generated
 */
public abstract class LCSClusterNodeServiceBaseImpl extends BaseServiceImpl
	implements LCSClusterNodeService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.osb.lcs.service.LCSClusterNodeServiceUtil} to access the l c s cluster node remote service.
	 */

	/**
	 * Returns the l c s cluster entry local service.
	 *
	 * @return the l c s cluster entry local service
	 */
	public com.liferay.osb.lcs.service.LCSClusterEntryLocalService getLCSClusterEntryLocalService() {
		return lcsClusterEntryLocalService;
	}

	/**
	 * Sets the l c s cluster entry local service.
	 *
	 * @param lcsClusterEntryLocalService the l c s cluster entry local service
	 */
	public void setLCSClusterEntryLocalService(
		com.liferay.osb.lcs.service.LCSClusterEntryLocalService lcsClusterEntryLocalService) {
		this.lcsClusterEntryLocalService = lcsClusterEntryLocalService;
	}

	/**
	 * Returns the l c s cluster entry remote service.
	 *
	 * @return the l c s cluster entry remote service
	 */
	public com.liferay.osb.lcs.service.LCSClusterEntryService getLCSClusterEntryService() {
		return lcsClusterEntryService;
	}

	/**
	 * Sets the l c s cluster entry remote service.
	 *
	 * @param lcsClusterEntryService the l c s cluster entry remote service
	 */
	public void setLCSClusterEntryService(
		com.liferay.osb.lcs.service.LCSClusterEntryService lcsClusterEntryService) {
		this.lcsClusterEntryService = lcsClusterEntryService;
	}

	/**
	 * Returns the l c s cluster entry persistence.
	 *
	 * @return the l c s cluster entry persistence
	 */
	public LCSClusterEntryPersistence getLCSClusterEntryPersistence() {
		return lcsClusterEntryPersistence;
	}

	/**
	 * Sets the l c s cluster entry persistence.
	 *
	 * @param lcsClusterEntryPersistence the l c s cluster entry persistence
	 */
	public void setLCSClusterEntryPersistence(
		LCSClusterEntryPersistence lcsClusterEntryPersistence) {
		this.lcsClusterEntryPersistence = lcsClusterEntryPersistence;
	}

	/**
	 * Returns the l c s cluster entry token local service.
	 *
	 * @return the l c s cluster entry token local service
	 */
	public com.liferay.osb.lcs.service.LCSClusterEntryTokenLocalService getLCSClusterEntryTokenLocalService() {
		return lcsClusterEntryTokenLocalService;
	}

	/**
	 * Sets the l c s cluster entry token local service.
	 *
	 * @param lcsClusterEntryTokenLocalService the l c s cluster entry token local service
	 */
	public void setLCSClusterEntryTokenLocalService(
		com.liferay.osb.lcs.service.LCSClusterEntryTokenLocalService lcsClusterEntryTokenLocalService) {
		this.lcsClusterEntryTokenLocalService = lcsClusterEntryTokenLocalService;
	}

	/**
	 * Returns the l c s cluster entry token remote service.
	 *
	 * @return the l c s cluster entry token remote service
	 */
	public com.liferay.osb.lcs.service.LCSClusterEntryTokenService getLCSClusterEntryTokenService() {
		return lcsClusterEntryTokenService;
	}

	/**
	 * Sets the l c s cluster entry token remote service.
	 *
	 * @param lcsClusterEntryTokenService the l c s cluster entry token remote service
	 */
	public void setLCSClusterEntryTokenService(
		com.liferay.osb.lcs.service.LCSClusterEntryTokenService lcsClusterEntryTokenService) {
		this.lcsClusterEntryTokenService = lcsClusterEntryTokenService;
	}

	/**
	 * Returns the l c s cluster entry token persistence.
	 *
	 * @return the l c s cluster entry token persistence
	 */
	public LCSClusterEntryTokenPersistence getLCSClusterEntryTokenPersistence() {
		return lcsClusterEntryTokenPersistence;
	}

	/**
	 * Sets the l c s cluster entry token persistence.
	 *
	 * @param lcsClusterEntryTokenPersistence the l c s cluster entry token persistence
	 */
	public void setLCSClusterEntryTokenPersistence(
		LCSClusterEntryTokenPersistence lcsClusterEntryTokenPersistence) {
		this.lcsClusterEntryTokenPersistence = lcsClusterEntryTokenPersistence;
	}

	/**
	 * Returns the l c s cluster node local service.
	 *
	 * @return the l c s cluster node local service
	 */
	public com.liferay.osb.lcs.service.LCSClusterNodeLocalService getLCSClusterNodeLocalService() {
		return lcsClusterNodeLocalService;
	}

	/**
	 * Sets the l c s cluster node local service.
	 *
	 * @param lcsClusterNodeLocalService the l c s cluster node local service
	 */
	public void setLCSClusterNodeLocalService(
		com.liferay.osb.lcs.service.LCSClusterNodeLocalService lcsClusterNodeLocalService) {
		this.lcsClusterNodeLocalService = lcsClusterNodeLocalService;
	}

	/**
	 * Returns the l c s cluster node remote service.
	 *
	 * @return the l c s cluster node remote service
	 */
	public LCSClusterNodeService getLCSClusterNodeService() {
		return lcsClusterNodeService;
	}

	/**
	 * Sets the l c s cluster node remote service.
	 *
	 * @param lcsClusterNodeService the l c s cluster node remote service
	 */
	public void setLCSClusterNodeService(
		LCSClusterNodeService lcsClusterNodeService) {
		this.lcsClusterNodeService = lcsClusterNodeService;
	}

	/**
	 * Returns the l c s cluster node persistence.
	 *
	 * @return the l c s cluster node persistence
	 */
	public LCSClusterNodePersistence getLCSClusterNodePersistence() {
		return lcsClusterNodePersistence;
	}

	/**
	 * Sets the l c s cluster node persistence.
	 *
	 * @param lcsClusterNodePersistence the l c s cluster node persistence
	 */
	public void setLCSClusterNodePersistence(
		LCSClusterNodePersistence lcsClusterNodePersistence) {
		this.lcsClusterNodePersistence = lcsClusterNodePersistence;
	}

	/**
	 * Returns the l c s cluster node finder.
	 *
	 * @return the l c s cluster node finder
	 */
	public LCSClusterNodeFinder getLCSClusterNodeFinder() {
		return lcsClusterNodeFinder;
	}

	/**
	 * Sets the l c s cluster node finder.
	 *
	 * @param lcsClusterNodeFinder the l c s cluster node finder
	 */
	public void setLCSClusterNodeFinder(
		LCSClusterNodeFinder lcsClusterNodeFinder) {
		this.lcsClusterNodeFinder = lcsClusterNodeFinder;
	}

	/**
	 * Returns the l c s cluster node uptime local service.
	 *
	 * @return the l c s cluster node uptime local service
	 */
	public com.liferay.osb.lcs.service.LCSClusterNodeUptimeLocalService getLCSClusterNodeUptimeLocalService() {
		return lcsClusterNodeUptimeLocalService;
	}

	/**
	 * Sets the l c s cluster node uptime local service.
	 *
	 * @param lcsClusterNodeUptimeLocalService the l c s cluster node uptime local service
	 */
	public void setLCSClusterNodeUptimeLocalService(
		com.liferay.osb.lcs.service.LCSClusterNodeUptimeLocalService lcsClusterNodeUptimeLocalService) {
		this.lcsClusterNodeUptimeLocalService = lcsClusterNodeUptimeLocalService;
	}

	/**
	 * Returns the l c s cluster node uptime remote service.
	 *
	 * @return the l c s cluster node uptime remote service
	 */
	public com.liferay.osb.lcs.service.LCSClusterNodeUptimeService getLCSClusterNodeUptimeService() {
		return lcsClusterNodeUptimeService;
	}

	/**
	 * Sets the l c s cluster node uptime remote service.
	 *
	 * @param lcsClusterNodeUptimeService the l c s cluster node uptime remote service
	 */
	public void setLCSClusterNodeUptimeService(
		com.liferay.osb.lcs.service.LCSClusterNodeUptimeService lcsClusterNodeUptimeService) {
		this.lcsClusterNodeUptimeService = lcsClusterNodeUptimeService;
	}

	/**
	 * Returns the l c s cluster node uptime persistence.
	 *
	 * @return the l c s cluster node uptime persistence
	 */
	public LCSClusterNodeUptimePersistence getLCSClusterNodeUptimePersistence() {
		return lcsClusterNodeUptimePersistence;
	}

	/**
	 * Sets the l c s cluster node uptime persistence.
	 *
	 * @param lcsClusterNodeUptimePersistence the l c s cluster node uptime persistence
	 */
	public void setLCSClusterNodeUptimePersistence(
		LCSClusterNodeUptimePersistence lcsClusterNodeUptimePersistence) {
		this.lcsClusterNodeUptimePersistence = lcsClusterNodeUptimePersistence;
	}

	/**
	 * Returns the l c s invitation local service.
	 *
	 * @return the l c s invitation local service
	 */
	public com.liferay.osb.lcs.service.LCSInvitationLocalService getLCSInvitationLocalService() {
		return lcsInvitationLocalService;
	}

	/**
	 * Sets the l c s invitation local service.
	 *
	 * @param lcsInvitationLocalService the l c s invitation local service
	 */
	public void setLCSInvitationLocalService(
		com.liferay.osb.lcs.service.LCSInvitationLocalService lcsInvitationLocalService) {
		this.lcsInvitationLocalService = lcsInvitationLocalService;
	}

	/**
	 * Returns the l c s invitation remote service.
	 *
	 * @return the l c s invitation remote service
	 */
	public com.liferay.osb.lcs.service.LCSInvitationService getLCSInvitationService() {
		return lcsInvitationService;
	}

	/**
	 * Sets the l c s invitation remote service.
	 *
	 * @param lcsInvitationService the l c s invitation remote service
	 */
	public void setLCSInvitationService(
		com.liferay.osb.lcs.service.LCSInvitationService lcsInvitationService) {
		this.lcsInvitationService = lcsInvitationService;
	}

	/**
	 * Returns the l c s invitation persistence.
	 *
	 * @return the l c s invitation persistence
	 */
	public LCSInvitationPersistence getLCSInvitationPersistence() {
		return lcsInvitationPersistence;
	}

	/**
	 * Sets the l c s invitation persistence.
	 *
	 * @param lcsInvitationPersistence the l c s invitation persistence
	 */
	public void setLCSInvitationPersistence(
		LCSInvitationPersistence lcsInvitationPersistence) {
		this.lcsInvitationPersistence = lcsInvitationPersistence;
	}

	/**
	 * Returns the l c s members local service.
	 *
	 * @return the l c s members local service
	 */
	public com.liferay.osb.lcs.service.LCSMembersLocalService getLCSMembersLocalService() {
		return lcsMembersLocalService;
	}

	/**
	 * Sets the l c s members local service.
	 *
	 * @param lcsMembersLocalService the l c s members local service
	 */
	public void setLCSMembersLocalService(
		com.liferay.osb.lcs.service.LCSMembersLocalService lcsMembersLocalService) {
		this.lcsMembersLocalService = lcsMembersLocalService;
	}

	/**
	 * Returns the l c s members remote service.
	 *
	 * @return the l c s members remote service
	 */
	public com.liferay.osb.lcs.service.LCSMembersService getLCSMembersService() {
		return lcsMembersService;
	}

	/**
	 * Sets the l c s members remote service.
	 *
	 * @param lcsMembersService the l c s members remote service
	 */
	public void setLCSMembersService(
		com.liferay.osb.lcs.service.LCSMembersService lcsMembersService) {
		this.lcsMembersService = lcsMembersService;
	}

	/**
	 * Returns the l c s message local service.
	 *
	 * @return the l c s message local service
	 */
	public com.liferay.osb.lcs.service.LCSMessageLocalService getLCSMessageLocalService() {
		return lcsMessageLocalService;
	}

	/**
	 * Sets the l c s message local service.
	 *
	 * @param lcsMessageLocalService the l c s message local service
	 */
	public void setLCSMessageLocalService(
		com.liferay.osb.lcs.service.LCSMessageLocalService lcsMessageLocalService) {
		this.lcsMessageLocalService = lcsMessageLocalService;
	}

	/**
	 * Returns the l c s message remote service.
	 *
	 * @return the l c s message remote service
	 */
	public com.liferay.osb.lcs.service.LCSMessageService getLCSMessageService() {
		return lcsMessageService;
	}

	/**
	 * Sets the l c s message remote service.
	 *
	 * @param lcsMessageService the l c s message remote service
	 */
	public void setLCSMessageService(
		com.liferay.osb.lcs.service.LCSMessageService lcsMessageService) {
		this.lcsMessageService = lcsMessageService;
	}

	/**
	 * Returns the l c s message persistence.
	 *
	 * @return the l c s message persistence
	 */
	public LCSMessagePersistence getLCSMessagePersistence() {
		return lcsMessagePersistence;
	}

	/**
	 * Sets the l c s message persistence.
	 *
	 * @param lcsMessagePersistence the l c s message persistence
	 */
	public void setLCSMessagePersistence(
		LCSMessagePersistence lcsMessagePersistence) {
		this.lcsMessagePersistence = lcsMessagePersistence;
	}

	/**
	 * Returns the l c s metadata local service.
	 *
	 * @return the l c s metadata local service
	 */
	public com.liferay.osb.lcs.service.LCSMetadataLocalService getLCSMetadataLocalService() {
		return lcsMetadataLocalService;
	}

	/**
	 * Sets the l c s metadata local service.
	 *
	 * @param lcsMetadataLocalService the l c s metadata local service
	 */
	public void setLCSMetadataLocalService(
		com.liferay.osb.lcs.service.LCSMetadataLocalService lcsMetadataLocalService) {
		this.lcsMetadataLocalService = lcsMetadataLocalService;
	}

	/**
	 * Returns the l c s metadata remote service.
	 *
	 * @return the l c s metadata remote service
	 */
	public com.liferay.osb.lcs.service.LCSMetadataService getLCSMetadataService() {
		return lcsMetadataService;
	}

	/**
	 * Sets the l c s metadata remote service.
	 *
	 * @param lcsMetadataService the l c s metadata remote service
	 */
	public void setLCSMetadataService(
		com.liferay.osb.lcs.service.LCSMetadataService lcsMetadataService) {
		this.lcsMetadataService = lcsMetadataService;
	}

	/**
	 * Returns the l c s metadata persistence.
	 *
	 * @return the l c s metadata persistence
	 */
	public LCSMetadataPersistence getLCSMetadataPersistence() {
		return lcsMetadataPersistence;
	}

	/**
	 * Sets the l c s metadata persistence.
	 *
	 * @param lcsMetadataPersistence the l c s metadata persistence
	 */
	public void setLCSMetadataPersistence(
		LCSMetadataPersistence lcsMetadataPersistence) {
		this.lcsMetadataPersistence = lcsMetadataPersistence;
	}

	/**
	 * Returns the l c s notification local service.
	 *
	 * @return the l c s notification local service
	 */
	public com.liferay.osb.lcs.service.LCSNotificationLocalService getLCSNotificationLocalService() {
		return lcsNotificationLocalService;
	}

	/**
	 * Sets the l c s notification local service.
	 *
	 * @param lcsNotificationLocalService the l c s notification local service
	 */
	public void setLCSNotificationLocalService(
		com.liferay.osb.lcs.service.LCSNotificationLocalService lcsNotificationLocalService) {
		this.lcsNotificationLocalService = lcsNotificationLocalService;
	}

	/**
	 * Returns the l c s notification remote service.
	 *
	 * @return the l c s notification remote service
	 */
	public com.liferay.osb.lcs.service.LCSNotificationService getLCSNotificationService() {
		return lcsNotificationService;
	}

	/**
	 * Sets the l c s notification remote service.
	 *
	 * @param lcsNotificationService the l c s notification remote service
	 */
	public void setLCSNotificationService(
		com.liferay.osb.lcs.service.LCSNotificationService lcsNotificationService) {
		this.lcsNotificationService = lcsNotificationService;
	}

	/**
	 * Returns the l c s notification persistence.
	 *
	 * @return the l c s notification persistence
	 */
	public LCSNotificationPersistence getLCSNotificationPersistence() {
		return lcsNotificationPersistence;
	}

	/**
	 * Sets the l c s notification persistence.
	 *
	 * @param lcsNotificationPersistence the l c s notification persistence
	 */
	public void setLCSNotificationPersistence(
		LCSNotificationPersistence lcsNotificationPersistence) {
		this.lcsNotificationPersistence = lcsNotificationPersistence;
	}

	/**
	 * Returns the l c s notification audit entry local service.
	 *
	 * @return the l c s notification audit entry local service
	 */
	public com.liferay.osb.lcs.service.LCSNotificationAuditEntryLocalService getLCSNotificationAuditEntryLocalService() {
		return lcsNotificationAuditEntryLocalService;
	}

	/**
	 * Sets the l c s notification audit entry local service.
	 *
	 * @param lcsNotificationAuditEntryLocalService the l c s notification audit entry local service
	 */
	public void setLCSNotificationAuditEntryLocalService(
		com.liferay.osb.lcs.service.LCSNotificationAuditEntryLocalService lcsNotificationAuditEntryLocalService) {
		this.lcsNotificationAuditEntryLocalService = lcsNotificationAuditEntryLocalService;
	}

	/**
	 * Returns the l c s notification audit entry persistence.
	 *
	 * @return the l c s notification audit entry persistence
	 */
	public LCSNotificationAuditEntryPersistence getLCSNotificationAuditEntryPersistence() {
		return lcsNotificationAuditEntryPersistence;
	}

	/**
	 * Sets the l c s notification audit entry persistence.
	 *
	 * @param lcsNotificationAuditEntryPersistence the l c s notification audit entry persistence
	 */
	public void setLCSNotificationAuditEntryPersistence(
		LCSNotificationAuditEntryPersistence lcsNotificationAuditEntryPersistence) {
		this.lcsNotificationAuditEntryPersistence = lcsNotificationAuditEntryPersistence;
	}

	/**
	 * Returns the l c s patch entry local service.
	 *
	 * @return the l c s patch entry local service
	 */
	public com.liferay.osb.lcs.service.LCSPatchEntryLocalService getLCSPatchEntryLocalService() {
		return lcsPatchEntryLocalService;
	}

	/**
	 * Sets the l c s patch entry local service.
	 *
	 * @param lcsPatchEntryLocalService the l c s patch entry local service
	 */
	public void setLCSPatchEntryLocalService(
		com.liferay.osb.lcs.service.LCSPatchEntryLocalService lcsPatchEntryLocalService) {
		this.lcsPatchEntryLocalService = lcsPatchEntryLocalService;
	}

	/**
	 * Returns the l c s patch entry persistence.
	 *
	 * @return the l c s patch entry persistence
	 */
	public LCSPatchEntryPersistence getLCSPatchEntryPersistence() {
		return lcsPatchEntryPersistence;
	}

	/**
	 * Sets the l c s patch entry persistence.
	 *
	 * @param lcsPatchEntryPersistence the l c s patch entry persistence
	 */
	public void setLCSPatchEntryPersistence(
		LCSPatchEntryPersistence lcsPatchEntryPersistence) {
		this.lcsPatchEntryPersistence = lcsPatchEntryPersistence;
	}

	/**
	 * Returns the l c s patching advisor remote service.
	 *
	 * @return the l c s patching advisor remote service
	 */
	public com.liferay.osb.lcs.service.LCSPatchingAdvisorService getLCSPatchingAdvisorService() {
		return lcsPatchingAdvisorService;
	}

	/**
	 * Sets the l c s patching advisor remote service.
	 *
	 * @param lcsPatchingAdvisorService the l c s patching advisor remote service
	 */
	public void setLCSPatchingAdvisorService(
		com.liferay.osb.lcs.service.LCSPatchingAdvisorService lcsPatchingAdvisorService) {
		this.lcsPatchingAdvisorService = lcsPatchingAdvisorService;
	}

	/**
	 * Returns the l c s project local service.
	 *
	 * @return the l c s project local service
	 */
	public com.liferay.osb.lcs.service.LCSProjectLocalService getLCSProjectLocalService() {
		return lcsProjectLocalService;
	}

	/**
	 * Sets the l c s project local service.
	 *
	 * @param lcsProjectLocalService the l c s project local service
	 */
	public void setLCSProjectLocalService(
		com.liferay.osb.lcs.service.LCSProjectLocalService lcsProjectLocalService) {
		this.lcsProjectLocalService = lcsProjectLocalService;
	}

	/**
	 * Returns the l c s project remote service.
	 *
	 * @return the l c s project remote service
	 */
	public com.liferay.osb.lcs.service.LCSProjectService getLCSProjectService() {
		return lcsProjectService;
	}

	/**
	 * Sets the l c s project remote service.
	 *
	 * @param lcsProjectService the l c s project remote service
	 */
	public void setLCSProjectService(
		com.liferay.osb.lcs.service.LCSProjectService lcsProjectService) {
		this.lcsProjectService = lcsProjectService;
	}

	/**
	 * Returns the l c s project persistence.
	 *
	 * @return the l c s project persistence
	 */
	public LCSProjectPersistence getLCSProjectPersistence() {
		return lcsProjectPersistence;
	}

	/**
	 * Sets the l c s project persistence.
	 *
	 * @param lcsProjectPersistence the l c s project persistence
	 */
	public void setLCSProjectPersistence(
		LCSProjectPersistence lcsProjectPersistence) {
		this.lcsProjectPersistence = lcsProjectPersistence;
	}

	/**
	 * Returns the l c s role local service.
	 *
	 * @return the l c s role local service
	 */
	public com.liferay.osb.lcs.service.LCSRoleLocalService getLCSRoleLocalService() {
		return lcsRoleLocalService;
	}

	/**
	 * Sets the l c s role local service.
	 *
	 * @param lcsRoleLocalService the l c s role local service
	 */
	public void setLCSRoleLocalService(
		com.liferay.osb.lcs.service.LCSRoleLocalService lcsRoleLocalService) {
		this.lcsRoleLocalService = lcsRoleLocalService;
	}

	/**
	 * Returns the l c s role remote service.
	 *
	 * @return the l c s role remote service
	 */
	public com.liferay.osb.lcs.service.LCSRoleService getLCSRoleService() {
		return lcsRoleService;
	}

	/**
	 * Sets the l c s role remote service.
	 *
	 * @param lcsRoleService the l c s role remote service
	 */
	public void setLCSRoleService(
		com.liferay.osb.lcs.service.LCSRoleService lcsRoleService) {
		this.lcsRoleService = lcsRoleService;
	}

	/**
	 * Returns the l c s role persistence.
	 *
	 * @return the l c s role persistence
	 */
	public LCSRolePersistence getLCSRolePersistence() {
		return lcsRolePersistence;
	}

	/**
	 * Sets the l c s role persistence.
	 *
	 * @param lcsRolePersistence the l c s role persistence
	 */
	public void setLCSRolePersistence(LCSRolePersistence lcsRolePersistence) {
		this.lcsRolePersistence = lcsRolePersistence;
	}

	/**
	 * Returns the l c s subscription entry local service.
	 *
	 * @return the l c s subscription entry local service
	 */
	public com.liferay.osb.lcs.service.LCSSubscriptionEntryLocalService getLCSSubscriptionEntryLocalService() {
		return lcsSubscriptionEntryLocalService;
	}

	/**
	 * Sets the l c s subscription entry local service.
	 *
	 * @param lcsSubscriptionEntryLocalService the l c s subscription entry local service
	 */
	public void setLCSSubscriptionEntryLocalService(
		com.liferay.osb.lcs.service.LCSSubscriptionEntryLocalService lcsSubscriptionEntryLocalService) {
		this.lcsSubscriptionEntryLocalService = lcsSubscriptionEntryLocalService;
	}

	/**
	 * Returns the l c s subscription entry remote service.
	 *
	 * @return the l c s subscription entry remote service
	 */
	public com.liferay.osb.lcs.service.LCSSubscriptionEntryService getLCSSubscriptionEntryService() {
		return lcsSubscriptionEntryService;
	}

	/**
	 * Sets the l c s subscription entry remote service.
	 *
	 * @param lcsSubscriptionEntryService the l c s subscription entry remote service
	 */
	public void setLCSSubscriptionEntryService(
		com.liferay.osb.lcs.service.LCSSubscriptionEntryService lcsSubscriptionEntryService) {
		this.lcsSubscriptionEntryService = lcsSubscriptionEntryService;
	}

	/**
	 * Returns the l c s subscription entry persistence.
	 *
	 * @return the l c s subscription entry persistence
	 */
	public LCSSubscriptionEntryPersistence getLCSSubscriptionEntryPersistence() {
		return lcsSubscriptionEntryPersistence;
	}

	/**
	 * Sets the l c s subscription entry persistence.
	 *
	 * @param lcsSubscriptionEntryPersistence the l c s subscription entry persistence
	 */
	public void setLCSSubscriptionEntryPersistence(
		LCSSubscriptionEntryPersistence lcsSubscriptionEntryPersistence) {
		this.lcsSubscriptionEntryPersistence = lcsSubscriptionEntryPersistence;
	}

	/**
	 * Returns the user l c s message local service.
	 *
	 * @return the user l c s message local service
	 */
	public com.liferay.osb.lcs.service.UserLCSMessageLocalService getUserLCSMessageLocalService() {
		return userLCSMessageLocalService;
	}

	/**
	 * Sets the user l c s message local service.
	 *
	 * @param userLCSMessageLocalService the user l c s message local service
	 */
	public void setUserLCSMessageLocalService(
		com.liferay.osb.lcs.service.UserLCSMessageLocalService userLCSMessageLocalService) {
		this.userLCSMessageLocalService = userLCSMessageLocalService;
	}

	/**
	 * Returns the user l c s message remote service.
	 *
	 * @return the user l c s message remote service
	 */
	public com.liferay.osb.lcs.service.UserLCSMessageService getUserLCSMessageService() {
		return userLCSMessageService;
	}

	/**
	 * Sets the user l c s message remote service.
	 *
	 * @param userLCSMessageService the user l c s message remote service
	 */
	public void setUserLCSMessageService(
		com.liferay.osb.lcs.service.UserLCSMessageService userLCSMessageService) {
		this.userLCSMessageService = userLCSMessageService;
	}

	/**
	 * Returns the user l c s message persistence.
	 *
	 * @return the user l c s message persistence
	 */
	public UserLCSMessagePersistence getUserLCSMessagePersistence() {
		return userLCSMessagePersistence;
	}

	/**
	 * Sets the user l c s message persistence.
	 *
	 * @param userLCSMessagePersistence the user l c s message persistence
	 */
	public void setUserLCSMessagePersistence(
		UserLCSMessagePersistence userLCSMessagePersistence) {
		this.userLCSMessagePersistence = userLCSMessagePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LCSClusterNodeService.class.getName();
	}

	protected Class<?> getModelClass() {
		return LCSClusterNode.class;
	}

	protected String getModelClassName() {
		return LCSClusterNode.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = lcsClusterNodePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.osb.lcs.service.LCSClusterEntryLocalService.class)
	protected com.liferay.osb.lcs.service.LCSClusterEntryLocalService lcsClusterEntryLocalService;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSClusterEntryService.class)
	protected com.liferay.osb.lcs.service.LCSClusterEntryService lcsClusterEntryService;
	@BeanReference(type = LCSClusterEntryPersistence.class)
	protected LCSClusterEntryPersistence lcsClusterEntryPersistence;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSClusterEntryTokenLocalService.class)
	protected com.liferay.osb.lcs.service.LCSClusterEntryTokenLocalService lcsClusterEntryTokenLocalService;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSClusterEntryTokenService.class)
	protected com.liferay.osb.lcs.service.LCSClusterEntryTokenService lcsClusterEntryTokenService;
	@BeanReference(type = LCSClusterEntryTokenPersistence.class)
	protected LCSClusterEntryTokenPersistence lcsClusterEntryTokenPersistence;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSClusterNodeLocalService.class)
	protected com.liferay.osb.lcs.service.LCSClusterNodeLocalService lcsClusterNodeLocalService;
	@BeanReference(type = LCSClusterNodeService.class)
	protected LCSClusterNodeService lcsClusterNodeService;
	@BeanReference(type = LCSClusterNodePersistence.class)
	protected LCSClusterNodePersistence lcsClusterNodePersistence;
	@BeanReference(type = LCSClusterNodeFinder.class)
	protected LCSClusterNodeFinder lcsClusterNodeFinder;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSClusterNodeUptimeLocalService.class)
	protected com.liferay.osb.lcs.service.LCSClusterNodeUptimeLocalService lcsClusterNodeUptimeLocalService;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSClusterNodeUptimeService.class)
	protected com.liferay.osb.lcs.service.LCSClusterNodeUptimeService lcsClusterNodeUptimeService;
	@BeanReference(type = LCSClusterNodeUptimePersistence.class)
	protected LCSClusterNodeUptimePersistence lcsClusterNodeUptimePersistence;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSInvitationLocalService.class)
	protected com.liferay.osb.lcs.service.LCSInvitationLocalService lcsInvitationLocalService;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSInvitationService.class)
	protected com.liferay.osb.lcs.service.LCSInvitationService lcsInvitationService;
	@BeanReference(type = LCSInvitationPersistence.class)
	protected LCSInvitationPersistence lcsInvitationPersistence;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSMembersLocalService.class)
	protected com.liferay.osb.lcs.service.LCSMembersLocalService lcsMembersLocalService;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSMembersService.class)
	protected com.liferay.osb.lcs.service.LCSMembersService lcsMembersService;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSMessageLocalService.class)
	protected com.liferay.osb.lcs.service.LCSMessageLocalService lcsMessageLocalService;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSMessageService.class)
	protected com.liferay.osb.lcs.service.LCSMessageService lcsMessageService;
	@BeanReference(type = LCSMessagePersistence.class)
	protected LCSMessagePersistence lcsMessagePersistence;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSMetadataLocalService.class)
	protected com.liferay.osb.lcs.service.LCSMetadataLocalService lcsMetadataLocalService;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSMetadataService.class)
	protected com.liferay.osb.lcs.service.LCSMetadataService lcsMetadataService;
	@BeanReference(type = LCSMetadataPersistence.class)
	protected LCSMetadataPersistence lcsMetadataPersistence;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSNotificationLocalService.class)
	protected com.liferay.osb.lcs.service.LCSNotificationLocalService lcsNotificationLocalService;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSNotificationService.class)
	protected com.liferay.osb.lcs.service.LCSNotificationService lcsNotificationService;
	@BeanReference(type = LCSNotificationPersistence.class)
	protected LCSNotificationPersistence lcsNotificationPersistence;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSNotificationAuditEntryLocalService.class)
	protected com.liferay.osb.lcs.service.LCSNotificationAuditEntryLocalService lcsNotificationAuditEntryLocalService;
	@BeanReference(type = LCSNotificationAuditEntryPersistence.class)
	protected LCSNotificationAuditEntryPersistence lcsNotificationAuditEntryPersistence;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSPatchEntryLocalService.class)
	protected com.liferay.osb.lcs.service.LCSPatchEntryLocalService lcsPatchEntryLocalService;
	@BeanReference(type = LCSPatchEntryPersistence.class)
	protected LCSPatchEntryPersistence lcsPatchEntryPersistence;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSPatchingAdvisorService.class)
	protected com.liferay.osb.lcs.service.LCSPatchingAdvisorService lcsPatchingAdvisorService;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSProjectLocalService.class)
	protected com.liferay.osb.lcs.service.LCSProjectLocalService lcsProjectLocalService;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSProjectService.class)
	protected com.liferay.osb.lcs.service.LCSProjectService lcsProjectService;
	@BeanReference(type = LCSProjectPersistence.class)
	protected LCSProjectPersistence lcsProjectPersistence;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSRoleLocalService.class)
	protected com.liferay.osb.lcs.service.LCSRoleLocalService lcsRoleLocalService;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSRoleService.class)
	protected com.liferay.osb.lcs.service.LCSRoleService lcsRoleService;
	@BeanReference(type = LCSRolePersistence.class)
	protected LCSRolePersistence lcsRolePersistence;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSSubscriptionEntryLocalService.class)
	protected com.liferay.osb.lcs.service.LCSSubscriptionEntryLocalService lcsSubscriptionEntryLocalService;
	@BeanReference(type = com.liferay.osb.lcs.service.LCSSubscriptionEntryService.class)
	protected com.liferay.osb.lcs.service.LCSSubscriptionEntryService lcsSubscriptionEntryService;
	@BeanReference(type = LCSSubscriptionEntryPersistence.class)
	protected LCSSubscriptionEntryPersistence lcsSubscriptionEntryPersistence;
	@BeanReference(type = com.liferay.osb.lcs.service.UserLCSMessageLocalService.class)
	protected com.liferay.osb.lcs.service.UserLCSMessageLocalService userLCSMessageLocalService;
	@BeanReference(type = com.liferay.osb.lcs.service.UserLCSMessageService.class)
	protected com.liferay.osb.lcs.service.UserLCSMessageService userLCSMessageService;
	@BeanReference(type = UserLCSMessagePersistence.class)
	protected UserLCSMessagePersistence userLCSMessagePersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}